import type { CatalogLib } from "./types.ts";

export const lists: CatalogLib = {
  name: "lists",
  description: "build, access, search, map/filter/fold, sort",
  primitives: [
    { name: "length", signature: "(length lst) → n" },
    { name: "append", signature: "(append lst ...) → list" },
    { name: "reverse", signature: "(reverse lst) → list" },
    { name: "list-ref", signature: "(list-ref lst i) → any", doc: "0-based." },
    { name: "list-tail", signature: "(list-tail lst i) → list", doc: "Drops the first i elements." },
    { name: "take", signature: "(take lst n) → list", doc: "First n elements; drop returns the rest." },
    { name: "drop", signature: "(drop lst n) → list" },
    { name: "first", signature: "(first lst) → any", doc: "second … tenth too; also last and rest." },
    { name: "last", signature: "(last lst) → any" },
    { name: "member", signature: "(member x lst) → list | #f", doc: "Tail starting at x (equal?), or #f. memq/memv use eq?/eqv?." },
    { name: "assoc", signature: "(assoc key alist) → pair | #f", doc: "Matching (key . val) pair (equal?), or #f. assq/assv use eq?/eqv?." },
    { name: "find", signature: "(find pred lst) → any | #f" },
    { name: "index-of", signature: "(index-of lst x) → n | #f", doc: "List first, then the element." },
    { name: "map", signature: "(map proc lst ...) → list", doc: "for-each instead when you only want side effects." },
    { name: "for-each", signature: "(for-each proc lst ...) → void" },
    { name: "filter", signature: "(filter pred lst) → list", doc: "remove / filter-not keep the complement." },
    { name: "remove", signature: "(remove pred lst) → list" },
    { name: "partition", signature: "(partition pred lst) → (values kept dropped)" },
    { name: "fold", signature: "(fold proc init lst) → any", doc: "SRFI-1: proc is called (elem acc); init seeds the accumulator. fold-right folds from the right." },
    { name: "reduce", signature: "(reduce proc ridentity lst) → any", doc: "Like fold but seeds with the first element; ridentity is used only for the empty list." },
    { name: "append-map", signature: "(append-map proc lst) → list" },
    { name: "filter-map", signature: "(filter-map proc lst) → list", doc: "map, then drop the #f results." },
    { name: "count", signature: "(count pred lst) → n" },
    { name: "any", signature: "(any pred lst) → any", doc: "every is the universal quantifier." },
    { name: "every", signature: "(every pred lst) → any" },
    { name: "iota", signature: "(iota n [start] [step]) → list", doc: "n elements. range is the Racket spelling: (range [start] end [step])." },
    { name: "range", signature: "(range end) | (range start end [step]) → list" },
    { name: "sort", signature: "(sort lst [less?]) → list", doc: "List first. less? defaults to a string compare — pass < for numbers." },
    { name: "remove-duplicates", signature: "(remove-duplicates lst) → list", doc: "delete-duplicates is the SRFI-1 spelling." },
    { name: "flatten", signature: "(flatten tree) → list" },
    { name: "make-list", signature: "(make-list n [fill]) → list" },
  ],
};
